// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7rHAcrQWl6UdwCkInqNM2ahl5PQorLBg',
    appId: '1:769287403463:web:15d87a31ec3c5ec34e0be2',
    messagingSenderId: '769287403463',
    projectId: 'inorbit-68c1b',
    authDomain: 'inorbit-68c1b.firebaseapp.com',
    storageBucket: 'inorbit-68c1b.firebasestorage.app',
    measurementId: 'G-QXWCWTX7VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxniQfO9dVq_-uifH9Lru3d63eeIL-vqs',
    appId: '1:769287403463:android:d79bc9b3ba34928a4e0be2',
    messagingSenderId: '769287403463',
    projectId: 'inorbit-68c1b',
    storageBucket: 'inorbit-68c1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiEcdx-JhZaLkQHeiEdxNyCGekWrW-8jQ',
    appId: '1:769287403463:ios:072ddbf2da1e843c4e0be2',
    messagingSenderId: '769287403463',
    projectId: 'inorbit-68c1b',
    storageBucket: 'inorbit-68c1b.firebasestorage.app',
    iosBundleId: 'com.example.inorbit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiEcdx-JhZaLkQHeiEdxNyCGekWrW-8jQ',
    appId: '1:769287403463:ios:072ddbf2da1e843c4e0be2',
    messagingSenderId: '769287403463',
    projectId: 'inorbit-68c1b',
    storageBucket: 'inorbit-68c1b.firebasestorage.app',
    iosBundleId: 'com.example.inorbit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7rHAcrQWl6UdwCkInqNM2ahl5PQorLBg',
    appId: '1:769287403463:web:e53e844ffd0584eb4e0be2',
    messagingSenderId: '769287403463',
    projectId: 'inorbit-68c1b',
    authDomain: 'inorbit-68c1b.firebaseapp.com',
    storageBucket: 'inorbit-68c1b.firebasestorage.app',
    measurementId: 'G-J25MFZLXSE',
  );
}
