import 'package:get_it/get_it.dart';
import 'package:inorbit/bloc/add_friend/add_friend_bloc.dart';
import 'package:inorbit/bloc/settings/settings_bloc.dart';
import 'package:inorbit/core/services/cloudinary_service.dart';
import 'package:inorbit/domain/usecases/add_friend.use_case.dart';
import 'package:inorbit/domain/usecases/add_moment_use_case.dart';
import 'package:inorbit/domain/usecases/delete_account_use_case.dart';

import '../../data/local/app_database.dart';
import '../../data/local/daos/friends_dao.dart';
import '../../data/local/daos/moments_dao.dart';
import '../../data/serializers/friend_firestore_serializer.dart';
import '../../data/serializers/friend_serializer.dart';
import '../../data/serializers/moment_firestore_serializer.dart';
import '../../data/serializers/moment_serializer.dart';
import '../../data/remote/firebase_friend_repository.dart';
import '../../data/remote/firebase_moment_repository.dart';
import '../../data/repositories/local_friend_repository.dart';
import '../../data/repositories/local_moment_repository.dart';
import '../../data/repositories/synced_friend_repository.dart';
import '../../data/repositories/synced_moment_repository.dart';
import '../../domain/repositories/friend_repository.dart';
import '../../domain/repositories/moment_repository.dart';
import '../../domain/usecases/get_stats.use_case.dart';
import '../../domain/usecases/sync_data.dart';
import '../../domain/usecases/watch_friends.dart';
import '../../bloc/home/home_bloc.dart';
import '../../bloc/stats/stats_bloc.dart';
import '../services/auth_service.dart';
import '../services/notification_service.dart';
import '../services/user_profile_service.dart';

final getIt = GetIt.instance;

void setupDependencies() {
  // Auth service — wraps Firebase Auth + Google/Apple sign-in
  getIt.registerLazySingleton<AuthService>(() => AuthService());

  // User profile service — reads/writes to Firestore users/{uid}
  getIt.registerLazySingleton<UserProfileService>(() => UserProfileService());

  // Notification service — schedules local birthday reminders
  getIt.registerSingleton<NotificationService>(NotificationService.instance);

  // Database — one connection for the app's lifetime
  getIt.registerSingleton<AppDatabase>(AppDatabase());

  // DAOs — lazy getters generated by Drift on AppDatabase
  getIt.registerSingleton<FriendsDao>(getIt<AppDatabase>().friendsDao);
  getIt.registerSingleton<MomentsDao>(getIt<AppDatabase>().momentsDao);

  // Serializers — stateless, safe to share
  getIt.registerSingleton<FriendSerializer>(const FriendSerializer());
  getIt.registerSingleton<MomentSerializer>(const MomentSerializer());

  // Firestore mappers — stateless, safe to share
  getIt.registerLazySingleton<FriendFirestoreSerializer>(
    () => FriendFirestoreSerializer(),
  );
  getIt.registerLazySingleton<MomentFirestoreSerializer>(
    () => MomentFirestoreSerializer(),
  );

  // Local repositories — concrete types registered for use by synced repos
  getIt.registerSingleton<LocalFriendRepository>(
    LocalFriendRepository(getIt<FriendsDao>(), getIt<FriendSerializer>()),
  );
  getIt.registerSingleton<LocalMomentRepository>(
    LocalMomentRepository(getIt<MomentsDao>(), getIt<MomentSerializer>()),
  );

  // Repositories — start with local-only; upgraded to synced after login
  getIt.registerSingleton<FriendRepository>(getIt<LocalFriendRepository>());
  getIt.registerSingleton<MomentRepository>(getIt<LocalMomentRepository>());

  // Use cases
  getIt.registerSingleton<WatchFriends>(
    WatchFriends(getIt<FriendRepository>()),
  );
  getIt.registerSingleton<GetStatsUseCase>(
    GetStatsUseCase(getIt<FriendRepository>(), getIt<MomentRepository>()),
  );

  // Use cases available before login
  getIt.registerLazySingleton<DeleteAccountUseCase>(
    () => DeleteAccountUseCase(getIt<AuthService>()),
  );

  // BLoCs — factory so each screen gets a fresh instance with its own state
  getIt.registerFactory<HomeBloc>(() => HomeBloc(getIt<WatchFriends>()));
  getIt.registerFactory<StatsBloc>(() => StatsBloc(getIt<GetStatsUseCase>()));
  getIt.registerFactory<SettingsBloc>(
    () => SettingsBloc(
      deleteAccount: getIt<DeleteAccountUseCase>(),
      authService: getIt<AuthService>(),
      userProfileService: getIt<UserProfileService>(),
      notificationService: getIt<NotificationService>(),
    ),
  );
}

/// Called once after successful login to wire up Firestore + synced repos.
/// Safe to call multiple times — returns early if already initialised.
void initRemoteRepositories(String userId) {
  if (getIt.isRegistered<FirebaseFriendRepository>()) return;

  getIt.registerSingleton<FirebaseFriendRepository>(
    FirebaseFriendRepository(userId, getIt<FriendFirestoreSerializer>()),
  );
  getIt.registerSingleton<FirebaseMomentRepository>(
    FirebaseMomentRepository(userId, getIt<MomentFirestoreSerializer>()),
  );
  getIt.registerSingleton<SyncedFriendRepository>(
    SyncedFriendRepository(
      getIt<LocalFriendRepository>(),
      getIt<FirebaseFriendRepository>(),
    ),
  );
  getIt.registerSingleton<SyncedMomentRepository>(
    SyncedMomentRepository(
      getIt<LocalMomentRepository>(),
      getIt<FirebaseMomentRepository>(),
    ),
  );

  // Re-register abstract repositories to use synced versions
  if (getIt.isRegistered<FriendRepository>()) {
    getIt.unregister<FriendRepository>();
  }
  getIt.registerSingleton<FriendRepository>(getIt<SyncedFriendRepository>());

  if (getIt.isRegistered<MomentRepository>()) {
    getIt.unregister<MomentRepository>();
  }
  getIt.registerSingleton<MomentRepository>(getIt<SyncedMomentRepository>());

  // SyncData use case — depends on both synced repos
  getIt.registerSingleton<SyncData>(
    SyncData(getIt<SyncedFriendRepository>(), getIt<SyncedMomentRepository>()),
  );

  // Re-register use cases with synced repositories
  if (getIt.isRegistered<WatchFriends>()) {
    getIt.unregister<WatchFriends>();
  }
  getIt.registerSingleton<WatchFriends>(
    WatchFriends(getIt<FriendRepository>()),
  );

  if (getIt.isRegistered<GetStatsUseCase>()) {
    getIt.unregister<GetStatsUseCase>();
  }
  getIt.registerSingleton<GetStatsUseCase>(
    GetStatsUseCase(getIt<FriendRepository>(), getIt<MomentRepository>()),
  );

  getIt.registerLazySingleton<CloudinaryService>(() => CloudinaryService());

  // Use cases
  getIt.registerSingleton<AddFriendUseCase>(
    AddFriendUseCase(getIt<FriendRepository>(), getIt<CloudinaryService>()),
  );
  getIt.registerSingleton<AddMomentUseCase>(
    AddMomentUseCase(getIt<MomentRepository>(), getIt<CloudinaryService>()),
  );

  // BLoC
  getIt.registerFactory<AddFriendBloc>(
    () => AddFriendBloc(getIt<AddFriendUseCase>()),
  );
}
